"""Initial migration

Revision ID: 27ccf3bb8f7f
Revises: cf29b7aff67d
Create Date: 2025-02-25 00:02:03.663575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ccf3bb8f7f'
down_revision: Union[str, None] = 'cf29b7aff67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
