"""Create user table

Revision ID: 4a5fd9901fd2
Revises: 27ccf3bb8f7f
Create Date: 2025-02-25 00:05:58.013075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5fd9901fd2'
down_revision: Union[str, None] = '27ccf3bb8f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
