"""Add user model

Revision ID: a359f5ddd0b7
Revises: b1b03c8ba5cd
Create Date: 2025-02-24 22:42:06.684831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a359f5ddd0b7'
down_revision: Union[str, None] = 'b1b03c8ba5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
